-- AlterTable
ALTER TABLE "Tournament" ADD COLUMN IF NOT EXISTS "haaOverallPlaces" INTEGER DEFAULT 2,
ADD COLUMN IF NOT EXISTS "haaMenPlaces" INTEGER DEFAULT 2,
ADD COLUMN IF NOT EXISTS "haaLadyPlaces" INTEGER DEFAULT 2,
ADD COLUMN IF NOT EXISTS "hoaOverallPlaces" INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS "hoaMenPlaces" INTEGER DEFAULT 2,
ADD COLUMN IF NOT EXISTS "hoaLadyPlaces" INTEGER DEFAULT 2;
