name: Deploy Demo to GitHub Pages

on:
  # Run on pushes to main branch
  push:
    branches: [main]
  
  # Allow manual trigger
  workflow_dispatch:

# Sets permissions for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build demo
        run: npm run build:demo
        env:
          NEXT_PUBLIC_DEMO_MODE: 'true'
          # If your repo is user.github.io, use: NEXT_PUBLIC_BASE_PATH: ''
          # If your repo is named something else, use: NEXT_PUBLIC_BASE_PATH: '/repo-name'
          # For example: NEXT_PUBLIC_BASE_PATH: '/claytargettracker'
          NEXT_PUBLIC_BASE_PATH: ''
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

